#!/bin/bash
#This script takes directory names as arguments on the command 
#line and says if they exist or not

#Define an array to collect the arguments
arg=( "$@" )
#Begin iteration loop to test each element of the array
for((i=0;i<$#;i++))
do
	#If the directory exists
	if [ -d ${arg[i]} ] && [ ! -f ${arg[i]} ]
		then
			#Print the directory name and "exists"
			echo "The directory"  ${arg[i]} "exists"
	#If the directory doesn't exist
	elif [ ! -d ${arg[i]} ] && [ ! -f ${arg[i]} ]
		then
			#Print the directory name and "doesn't exist"
			echo ${arg[i]} "doesn't exist"
	fi

	#If the file exists
	if [ -f ${arg[i]} ] && [ ! -d ${arg[i]} ]
		then
			#Print the file name and "exists"
			echo "The file"  ${arg[i]} "exists"
	#If the file doesn't exist
	elif [ ! -f ${arg[i]} ]  && [ ! -d ${arg[i]} ]
		then
			#Print the file name and "doesn't exist"
			echo ${arg[i]} "doesn't exist"
	fi
done
